# Generated by Django 2.1.3 on 2018-11-26 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20181126_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0, verbose_name='轮播图优先级')),
                ('image_url', models.URLField(verbose_name='轮播图图片链接')),
                ('link_to', models.URLField(verbose_name='轮播图跳转链接')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'ordering': ['-priority'],
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pub_time'], 'verbose_name': '新闻评论', 'verbose_name_plural': '新闻评论'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='news.News', verbose_name='评论所属的新闻'),
        ),
    ]
