# Generated by Django 2.1.3 on 2018-12-01 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='订单金额')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='订单生成时间')),
                ('istype', models.SmallIntegerField(choices=[(1, '支付宝'), (2, '微信')], verbose_name='支付类型')),
                ('status', models.SmallIntegerField(choices=[(1, '未支付'), (2, '支付成功')], verbose_name='订单状态')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.Course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '订单表',
                'verbose_name_plural': '订单表',
            },
        ),
    ]
