# Generated by Django 2.1.3 on 2018-12-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_courseorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorder',
            name='istype',
            field=models.SmallIntegerField(choices=[(0, '未知'), (1, '支付宝'), (2, '微信')], default=0, verbose_name='支付类型'),
        ),
    ]
