# Generated by Django 2.1.3 on 2018-12-01 08:30

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20181201_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorder',
            name='id',
        ),
        migrations.AddField(
            model_name='courseorder',
            name='uid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='主键'),
        ),
    ]
