# Generated by Django 2.1.3 on 2018-12-03 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20181201_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseorder',
            options={'verbose_name': '课程订单表', 'verbose_name_plural': '课程订单表'},
        ),
    ]
