# Generated by Django 2.1.3 on 2018-12-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('profile', models.CharField(max_length=100, verbose_name='简介')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='价格')),
                ('path', models.FilePathField(verbose_name='存储路径')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
            ],
            options={
                'verbose_name': '付费资讯',
                'verbose_name_plural': '付费资讯',
            },
        ),
    ]
