# Generated by Django 2.1.3 on 2018-12-03 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayinfoOrder',
            fields=[
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='主键')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='订单金额')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='订单生成时间')),
                ('istype', models.SmallIntegerField(choices=[(0, '未知'), (1, '支付宝'), (2, '微信')], default=0, verbose_name='支付类型')),
                ('status', models.SmallIntegerField(choices=[(1, '未支付'), (2, '支付成功')], verbose_name='订单状态')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('payinfo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payinfo.Payinfo', verbose_name='付费资讯')),
            ],
            options={
                'verbose_name': '付费资讯订单表',
                'verbose_name_plural': '付费资讯订单表',
            },
        ),
    ]
